// Comprehensive list of UK cities, large towns, and metropolitan areas.
// Sourced from ONS / Royal Charter city list + major towns. Used to standardise
// location data across the platform — free-text city entry is no longer allowed.

export type UkCountry = "England" | "Scotland" | "Wales" | "Northern Ireland";

export type UkCity = {
  city: string;
  region: string;
  country: UkCountry;
  /** Nearby cities/towns for lead-matching expansion. Names must match `city`. */
  nearby?: string[];
};

export const UK_CITIES: UkCity[] = [
  // ===== England — London & South East =====
  { city: "London", region: "Greater London", country: "England", nearby: ["Croydon", "Romford", "Bromley", "Watford", "Ilford", "Enfield"] },
  { city: "Croydon", region: "Greater London", country: "England", nearby: ["London", "Bromley", "Sutton"] },
  { city: "Bromley", region: "Greater London", country: "England", nearby: ["London", "Croydon"] },
  { city: "Romford", region: "Greater London", country: "England", nearby: ["London", "Ilford"] },
  { city: "Ilford", region: "Greater London", country: "England", nearby: ["London", "Romford"] },
  { city: "Enfield", region: "Greater London", country: "England", nearby: ["London"] },
  { city: "Sutton", region: "Greater London", country: "England", nearby: ["London", "Croydon"] },
  { city: "Kingston upon Thames", region: "Greater London", country: "England", nearby: ["London"] },
  { city: "Watford", region: "Hertfordshire", country: "England", nearby: ["London", "St Albans", "Hemel Hempstead"] },
  { city: "St Albans", region: "Hertfordshire", country: "England", nearby: ["Watford", "Hemel Hempstead"] },
  { city: "Hemel Hempstead", region: "Hertfordshire", country: "England", nearby: ["Watford", "St Albans"] },
  { city: "Stevenage", region: "Hertfordshire", country: "England" },
  { city: "Hertford", region: "Hertfordshire", country: "England" },
  { city: "Brighton", region: "East Sussex", country: "England", nearby: ["Hove", "Worthing", "Eastbourne"] },
  { city: "Hove", region: "East Sussex", country: "England", nearby: ["Brighton", "Worthing"] },
  { city: "Eastbourne", region: "East Sussex", country: "England", nearby: ["Brighton", "Hastings"] },
  { city: "Hastings", region: "East Sussex", country: "England", nearby: ["Eastbourne"] },
  { city: "Worthing", region: "West Sussex", country: "England", nearby: ["Brighton", "Chichester"] },
  { city: "Crawley", region: "West Sussex", country: "England", nearby: ["Horsham"] },
  { city: "Horsham", region: "West Sussex", country: "England", nearby: ["Crawley"] },
  { city: "Chichester", region: "West Sussex", country: "England", nearby: ["Worthing", "Portsmouth"] },
  { city: "Portsmouth", region: "Hampshire", country: "England", nearby: ["Southampton", "Chichester", "Gosport"] },
  { city: "Southampton", region: "Hampshire", country: "England", nearby: ["Portsmouth", "Winchester", "Bournemouth"] },
  { city: "Winchester", region: "Hampshire", country: "England", nearby: ["Southampton", "Basingstoke"] },
  { city: "Basingstoke", region: "Hampshire", country: "England", nearby: ["Winchester", "Reading"] },
  { city: "Gosport", region: "Hampshire", country: "England", nearby: ["Portsmouth"] },
  { city: "Fareham", region: "Hampshire", country: "England", nearby: ["Portsmouth", "Southampton"] },
  { city: "Andover", region: "Hampshire", country: "England" },
  { city: "Aldershot", region: "Hampshire", country: "England", nearby: ["Farnborough", "Guildford"] },
  { city: "Farnborough", region: "Hampshire", country: "England", nearby: ["Aldershot"] },
  { city: "Reading", region: "Berkshire", country: "England", nearby: ["Wokingham", "Bracknell", "Slough"] },
  { city: "Slough", region: "Berkshire", country: "England", nearby: ["Reading", "Windsor", "London"] },
  { city: "Bracknell", region: "Berkshire", country: "England", nearby: ["Reading", "Wokingham"] },
  { city: "Wokingham", region: "Berkshire", country: "England", nearby: ["Reading", "Bracknell"] },
  { city: "Windsor", region: "Berkshire", country: "England", nearby: ["Slough", "Maidenhead"] },
  { city: "Maidenhead", region: "Berkshire", country: "England", nearby: ["Windsor", "Slough"] },
  { city: "Newbury", region: "Berkshire", country: "England", nearby: ["Reading"] },
  { city: "Oxford", region: "Oxfordshire", country: "England", nearby: ["Banbury", "Abingdon", "Reading"] },
  { city: "Banbury", region: "Oxfordshire", country: "England", nearby: ["Oxford"] },
  { city: "Abingdon", region: "Oxfordshire", country: "England", nearby: ["Oxford"] },
  { city: "Milton Keynes", region: "Buckinghamshire", country: "England", nearby: ["Bedford", "Luton", "Northampton"] },
  { city: "High Wycombe", region: "Buckinghamshire", country: "England", nearby: ["Aylesbury"] },
  { city: "Aylesbury", region: "Buckinghamshire", country: "England", nearby: ["High Wycombe", "Milton Keynes"] },
  { city: "Luton", region: "Bedfordshire", country: "England", nearby: ["Dunstable", "Bedford", "Milton Keynes"] },
  { city: "Bedford", region: "Bedfordshire", country: "England", nearby: ["Luton", "Milton Keynes"] },
  { city: "Dunstable", region: "Bedfordshire", country: "England", nearby: ["Luton"] },
  { city: "Guildford", region: "Surrey", country: "England", nearby: ["Woking", "Aldershot"] },
  { city: "Woking", region: "Surrey", country: "England", nearby: ["Guildford"] },
  { city: "Camberley", region: "Surrey", country: "England", nearby: ["Aldershot", "Farnborough"] },
  { city: "Epsom", region: "Surrey", country: "England", nearby: ["London", "Sutton"] },
  { city: "Redhill", region: "Surrey", country: "England", nearby: ["Reigate", "Crawley"] },
  { city: "Reigate", region: "Surrey", country: "England", nearby: ["Redhill"] },
  { city: "Canterbury", region: "Kent", country: "England", nearby: ["Margate", "Ramsgate"] },
  { city: "Maidstone", region: "Kent", country: "England", nearby: ["Tonbridge", "Tunbridge Wells"] },
  { city: "Tonbridge", region: "Kent", country: "England", nearby: ["Maidstone", "Tunbridge Wells"] },
  { city: "Tunbridge Wells", region: "Kent", country: "England", nearby: ["Tonbridge", "Maidstone"] },
  { city: "Rochester", region: "Kent", country: "England", nearby: ["Chatham", "Gillingham"] },
  { city: "Chatham", region: "Kent", country: "England", nearby: ["Rochester", "Gillingham"] },
  { city: "Gillingham", region: "Kent", country: "England", nearby: ["Chatham", "Rochester"] },
  { city: "Dover", region: "Kent", country: "England", nearby: ["Folkestone"] },
  { city: "Folkestone", region: "Kent", country: "England", nearby: ["Dover"] },
  { city: "Margate", region: "Kent", country: "England", nearby: ["Ramsgate", "Canterbury"] },
  { city: "Ramsgate", region: "Kent", country: "England", nearby: ["Margate", "Canterbury"] },
  { city: "Ashford", region: "Kent", country: "England" },
  { city: "Dartford", region: "Kent", country: "England", nearby: ["London"] },

  // ===== England — South West =====
  { city: "Bristol", region: "South West", country: "England", nearby: ["Bath", "Weston-super-Mare", "Gloucester"] },
  { city: "Bath", region: "Somerset", country: "England", nearby: ["Bristol"] },
  { city: "Weston-super-Mare", region: "Somerset", country: "England", nearby: ["Bristol"] },
  { city: "Taunton", region: "Somerset", country: "England", nearby: ["Yeovil"] },
  { city: "Yeovil", region: "Somerset", country: "England", nearby: ["Taunton"] },
  { city: "Wells", region: "Somerset", country: "England" },
  { city: "Exeter", region: "Devon", country: "England", nearby: ["Torquay", "Plymouth"] },
  { city: "Plymouth", region: "Devon", country: "England", nearby: ["Exeter"] },
  { city: "Torquay", region: "Devon", country: "England", nearby: ["Paignton", "Exeter"] },
  { city: "Paignton", region: "Devon", country: "England", nearby: ["Torquay"] },
  { city: "Truro", region: "Cornwall", country: "England", nearby: ["Falmouth", "St Austell"] },
  { city: "Falmouth", region: "Cornwall", country: "England", nearby: ["Truro"] },
  { city: "St Austell", region: "Cornwall", country: "England", nearby: ["Truro"] },
  { city: "Newquay", region: "Cornwall", country: "England" },
  { city: "Penzance", region: "Cornwall", country: "England" },
  { city: "Bournemouth", region: "Dorset", country: "England", nearby: ["Poole", "Christchurch", "Southampton"] },
  { city: "Poole", region: "Dorset", country: "England", nearby: ["Bournemouth"] },
  { city: "Christchurch", region: "Dorset", country: "England", nearby: ["Bournemouth"] },
  { city: "Dorchester", region: "Dorset", country: "England", nearby: ["Weymouth"] },
  { city: "Weymouth", region: "Dorset", country: "England", nearby: ["Dorchester"] },
  { city: "Salisbury", region: "Wiltshire", country: "England", nearby: ["Southampton"] },
  { city: "Swindon", region: "Wiltshire", country: "England", nearby: ["Oxford"] },
  { city: "Chippenham", region: "Wiltshire", country: "England" },
  { city: "Gloucester", region: "Gloucestershire", country: "England", nearby: ["Cheltenham", "Bristol"] },
  { city: "Cheltenham", region: "Gloucestershire", country: "England", nearby: ["Gloucester"] },

  // ===== England — East =====
  { city: "Cambridge", region: "Cambridgeshire", country: "England", nearby: ["Ely", "Peterborough"] },
  { city: "Peterborough", region: "Cambridgeshire", country: "England", nearby: ["Cambridge"] },
  { city: "Ely", region: "Cambridgeshire", country: "England", nearby: ["Cambridge"] },
  { city: "Huntingdon", region: "Cambridgeshire", country: "England", nearby: ["Cambridge", "Peterborough"] },
  { city: "Norwich", region: "Norfolk", country: "England", nearby: ["Great Yarmouth"] },
  { city: "Great Yarmouth", region: "Norfolk", country: "England", nearby: ["Norwich"] },
  { city: "King's Lynn", region: "Norfolk", country: "England" },
  { city: "Ipswich", region: "Suffolk", country: "England", nearby: ["Colchester"] },
  { city: "Bury St Edmunds", region: "Suffolk", country: "England" },
  { city: "Lowestoft", region: "Suffolk", country: "England" },
  { city: "Colchester", region: "Essex", country: "England", nearby: ["Ipswich", "Chelmsford"] },
  { city: "Chelmsford", region: "Essex", country: "England", nearby: ["Colchester", "Basildon"] },
  { city: "Basildon", region: "Essex", country: "England", nearby: ["Chelmsford", "Southend-on-Sea"] },
  { city: "Southend-on-Sea", region: "Essex", country: "England", nearby: ["Basildon"] },
  { city: "Harlow", region: "Essex", country: "England", nearby: ["London"] },

  // ===== England — Midlands =====
  { city: "Birmingham", region: "West Midlands", country: "England", nearby: ["Wolverhampton", "Solihull", "West Bromwich", "Dudley", "Walsall", "Coventry"] },
  { city: "Coventry", region: "West Midlands", country: "England", nearby: ["Birmingham", "Solihull", "Warwick"] },
  { city: "Wolverhampton", region: "West Midlands", country: "England", nearby: ["Birmingham", "Walsall", "Dudley"] },
  { city: "Dudley", region: "West Midlands", country: "England", nearby: ["Birmingham", "Wolverhampton"] },
  { city: "Walsall", region: "West Midlands", country: "England", nearby: ["Birmingham", "Wolverhampton"] },
  { city: "West Bromwich", region: "West Midlands", country: "England", nearby: ["Birmingham"] },
  { city: "Solihull", region: "West Midlands", country: "England", nearby: ["Birmingham", "Coventry"] },
  { city: "Lichfield", region: "Staffordshire", country: "England", nearby: ["Birmingham", "Tamworth"] },
  { city: "Tamworth", region: "Staffordshire", country: "England", nearby: ["Lichfield", "Birmingham"] },
  { city: "Stoke-on-Trent", region: "Staffordshire", country: "England", nearby: ["Stafford", "Newcastle-under-Lyme"] },
  { city: "Stafford", region: "Staffordshire", country: "England", nearby: ["Stoke-on-Trent"] },
  { city: "Newcastle-under-Lyme", region: "Staffordshire", country: "England", nearby: ["Stoke-on-Trent"] },
  { city: "Warwick", region: "Warwickshire", country: "England", nearby: ["Leamington Spa", "Coventry"] },
  { city: "Leamington Spa", region: "Warwickshire", country: "England", nearby: ["Warwick"] },
  { city: "Rugby", region: "Warwickshire", country: "England", nearby: ["Coventry"] },
  { city: "Nuneaton", region: "Warwickshire", country: "England", nearby: ["Coventry"] },
  { city: "Stratford-upon-Avon", region: "Warwickshire", country: "England", nearby: ["Warwick"] },
  { city: "Worcester", region: "Worcestershire", country: "England", nearby: ["Kidderminster", "Redditch"] },
  { city: "Kidderminster", region: "Worcestershire", country: "England", nearby: ["Worcester"] },
  { city: "Redditch", region: "Worcestershire", country: "England", nearby: ["Worcester", "Birmingham"] },
  { city: "Hereford", region: "Herefordshire", country: "England" },
  { city: "Shrewsbury", region: "Shropshire", country: "England", nearby: ["Telford"] },
  { city: "Telford", region: "Shropshire", country: "England", nearby: ["Shrewsbury"] },
  { city: "Nottingham", region: "Nottinghamshire", country: "England", nearby: ["Derby", "Mansfield"] },
  { city: "Mansfield", region: "Nottinghamshire", country: "England", nearby: ["Nottingham"] },
  { city: "Newark-on-Trent", region: "Nottinghamshire", country: "England", nearby: ["Nottingham"] },
  { city: "Derby", region: "Derbyshire", country: "England", nearby: ["Nottingham", "Chesterfield"] },
  { city: "Chesterfield", region: "Derbyshire", country: "England", nearby: ["Sheffield", "Derby"] },
  { city: "Buxton", region: "Derbyshire", country: "England" },
  { city: "Leicester", region: "Leicestershire", country: "England", nearby: ["Loughborough", "Hinckley"] },
  { city: "Loughborough", region: "Leicestershire", country: "England", nearby: ["Leicester"] },
  { city: "Hinckley", region: "Leicestershire", country: "England", nearby: ["Leicester"] },
  { city: "Lincoln", region: "Lincolnshire", country: "England", nearby: ["Grimsby", "Boston"] },
  { city: "Grimsby", region: "Lincolnshire", country: "England", nearby: ["Lincoln"] },
  { city: "Boston", region: "Lincolnshire", country: "England", nearby: ["Lincoln"] },
  { city: "Scunthorpe", region: "Lincolnshire", country: "England" },
  { city: "Northampton", region: "Northamptonshire", country: "England", nearby: ["Kettering", "Wellingborough", "Milton Keynes"] },
  { city: "Kettering", region: "Northamptonshire", country: "England", nearby: ["Northampton"] },
  { city: "Wellingborough", region: "Northamptonshire", country: "England", nearby: ["Northampton"] },
  { city: "Corby", region: "Northamptonshire", country: "England", nearby: ["Kettering"] },

  // ===== England — Yorkshire & The Humber =====
  { city: "Leeds", region: "West Yorkshire", country: "England", nearby: ["Bradford", "Wakefield", "Huddersfield", "Halifax"] },
  { city: "Bradford", region: "West Yorkshire", country: "England", nearby: ["Leeds", "Halifax", "Huddersfield"] },
  { city: "Wakefield", region: "West Yorkshire", country: "England", nearby: ["Leeds"] },
  { city: "Huddersfield", region: "West Yorkshire", country: "England", nearby: ["Bradford", "Halifax", "Leeds"] },
  { city: "Halifax", region: "West Yorkshire", country: "England", nearby: ["Bradford", "Huddersfield"] },
  { city: "Sheffield", region: "South Yorkshire", country: "England", nearby: ["Rotherham", "Barnsley", "Doncaster", "Chesterfield"] },
  { city: "Rotherham", region: "South Yorkshire", country: "England", nearby: ["Sheffield", "Doncaster"] },
  { city: "Doncaster", region: "South Yorkshire", country: "England", nearby: ["Sheffield", "Rotherham"] },
  { city: "Barnsley", region: "South Yorkshire", country: "England", nearby: ["Sheffield", "Wakefield"] },
  { city: "York", region: "North Yorkshire", country: "England", nearby: ["Harrogate", "Selby"] },
  { city: "Harrogate", region: "North Yorkshire", country: "England", nearby: ["York", "Leeds"] },
  { city: "Scarborough", region: "North Yorkshire", country: "England" },
  { city: "Middlesbrough", region: "North Yorkshire", country: "England", nearby: ["Stockton-on-Tees", "Hartlepool"] },
  { city: "Hull", region: "East Riding of Yorkshire", country: "England", nearby: ["Beverley", "Grimsby"] },
  { city: "Beverley", region: "East Riding of Yorkshire", country: "England", nearby: ["Hull"] },

  // ===== England — North West =====
  { city: "Manchester", region: "Greater Manchester", country: "England", nearby: ["Salford", "Stockport", "Bolton", "Oldham", "Rochdale", "Bury", "Wigan", "Trafford"] },
  { city: "Salford", region: "Greater Manchester", country: "England", nearby: ["Manchester"] },
  { city: "Stockport", region: "Greater Manchester", country: "England", nearby: ["Manchester"] },
  { city: "Bolton", region: "Greater Manchester", country: "England", nearby: ["Manchester", "Bury", "Wigan"] },
  { city: "Oldham", region: "Greater Manchester", country: "England", nearby: ["Manchester", "Rochdale"] },
  { city: "Rochdale", region: "Greater Manchester", country: "England", nearby: ["Manchester", "Oldham", "Bury"] },
  { city: "Bury", region: "Greater Manchester", country: "England", nearby: ["Manchester", "Bolton", "Rochdale"] },
  { city: "Wigan", region: "Greater Manchester", country: "England", nearby: ["Manchester", "Bolton", "St Helens"] },
  { city: "Trafford", region: "Greater Manchester", country: "England", nearby: ["Manchester"] },
  { city: "Altrincham", region: "Greater Manchester", country: "England", nearby: ["Manchester"] },
  { city: "Liverpool", region: "Merseyside", country: "England", nearby: ["Birkenhead", "Bootle", "St Helens", "Southport"] },
  { city: "Birkenhead", region: "Merseyside", country: "England", nearby: ["Liverpool"] },
  { city: "St Helens", region: "Merseyside", country: "England", nearby: ["Liverpool", "Wigan", "Warrington"] },
  { city: "Southport", region: "Merseyside", country: "England", nearby: ["Liverpool"] },
  { city: "Bootle", region: "Merseyside", country: "England", nearby: ["Liverpool"] },
  { city: "Warrington", region: "Cheshire", country: "England", nearby: ["St Helens", "Manchester", "Chester"] },
  { city: "Chester", region: "Cheshire", country: "England", nearby: ["Ellesmere Port", "Wrexham"] },
  { city: "Ellesmere Port", region: "Cheshire", country: "England", nearby: ["Chester"] },
  { city: "Crewe", region: "Cheshire", country: "England", nearby: ["Chester"] },
  { city: "Macclesfield", region: "Cheshire", country: "England", nearby: ["Stockport", "Manchester"] },
  { city: "Preston", region: "Lancashire", country: "England", nearby: ["Blackburn", "Blackpool", "Lancaster"] },
  { city: "Blackpool", region: "Lancashire", country: "England", nearby: ["Preston", "Lancaster"] },
  { city: "Blackburn", region: "Lancashire", country: "England", nearby: ["Preston", "Burnley"] },
  { city: "Burnley", region: "Lancashire", country: "England", nearby: ["Blackburn", "Preston"] },
  { city: "Lancaster", region: "Lancashire", country: "England", nearby: ["Preston", "Blackpool"] },
  { city: "Carlisle", region: "Cumbria", country: "England" },
  { city: "Barrow-in-Furness", region: "Cumbria", country: "England" },
  { city: "Kendal", region: "Cumbria", country: "England" },

  // ===== England — North East =====
  { city: "Newcastle upon Tyne", region: "Tyne and Wear", country: "England", nearby: ["Gateshead", "Sunderland", "North Shields", "South Shields"] },
  { city: "Gateshead", region: "Tyne and Wear", country: "England", nearby: ["Newcastle upon Tyne"] },
  { city: "Sunderland", region: "Tyne and Wear", country: "England", nearby: ["Newcastle upon Tyne", "Durham"] },
  { city: "North Shields", region: "Tyne and Wear", country: "England", nearby: ["Newcastle upon Tyne"] },
  { city: "South Shields", region: "Tyne and Wear", country: "England", nearby: ["Newcastle upon Tyne", "Sunderland"] },
  { city: "Durham", region: "County Durham", country: "England", nearby: ["Sunderland", "Newcastle upon Tyne"] },
  { city: "Darlington", region: "County Durham", country: "England", nearby: ["Stockton-on-Tees"] },
  { city: "Hartlepool", region: "County Durham", country: "England", nearby: ["Middlesbrough", "Stockton-on-Tees"] },
  { city: "Stockton-on-Tees", region: "County Durham", country: "England", nearby: ["Middlesbrough", "Darlington"] },

  // ===== Scotland =====
  { city: "Glasgow", region: "Greater Glasgow", country: "Scotland", nearby: ["Paisley", "East Kilbride", "Hamilton", "Motherwell", "Clydebank"] },
  { city: "Paisley", region: "Renfrewshire", country: "Scotland", nearby: ["Glasgow"] },
  { city: "Clydebank", region: "West Dunbartonshire", country: "Scotland", nearby: ["Glasgow"] },
  { city: "East Kilbride", region: "South Lanarkshire", country: "Scotland", nearby: ["Glasgow", "Hamilton"] },
  { city: "Hamilton", region: "South Lanarkshire", country: "Scotland", nearby: ["Motherwell", "East Kilbride", "Glasgow"] },
  { city: "Motherwell", region: "North Lanarkshire", country: "Scotland", nearby: ["Hamilton", "Glasgow"] },
  { city: "Coatbridge", region: "North Lanarkshire", country: "Scotland", nearby: ["Glasgow", "Airdrie"] },
  { city: "Airdrie", region: "North Lanarkshire", country: "Scotland", nearby: ["Coatbridge", "Glasgow"] },
  { city: "Edinburgh", region: "Lothian", country: "Scotland", nearby: ["Livingston", "Musselburgh", "Dunfermline"] },
  { city: "Livingston", region: "West Lothian", country: "Scotland", nearby: ["Edinburgh"] },
  { city: "Musselburgh", region: "East Lothian", country: "Scotland", nearby: ["Edinburgh"] },
  { city: "Dunfermline", region: "Fife", country: "Scotland", nearby: ["Edinburgh", "Kirkcaldy"] },
  { city: "Kirkcaldy", region: "Fife", country: "Scotland", nearby: ["Dunfermline"] },
  { city: "St Andrews", region: "Fife", country: "Scotland" },
  { city: "Aberdeen", region: "Aberdeenshire", country: "Scotland" },
  { city: "Dundee", region: "Tayside", country: "Scotland", nearby: ["Perth"] },
  { city: "Perth", region: "Perth and Kinross", country: "Scotland", nearby: ["Dundee"] },
  { city: "Stirling", region: "Stirling", country: "Scotland", nearby: ["Falkirk"] },
  { city: "Falkirk", region: "Falkirk", country: "Scotland", nearby: ["Stirling"] },
  { city: "Inverness", region: "Highland", country: "Scotland" },
  { city: "Ayr", region: "South Ayrshire", country: "Scotland", nearby: ["Kilmarnock"] },
  { city: "Kilmarnock", region: "East Ayrshire", country: "Scotland", nearby: ["Ayr"] },
  { city: "Greenock", region: "Inverclyde", country: "Scotland", nearby: ["Glasgow"] },
  { city: "Dumfries", region: "Dumfries and Galloway", country: "Scotland" },
  { city: "Fort William", region: "Highland", country: "Scotland" },
  { city: "Oban", region: "Argyll and Bute", country: "Scotland" },
  { city: "Elgin", region: "Moray", country: "Scotland" },

  // ===== Wales =====
  { city: "Cardiff", region: "South Wales", country: "Wales", nearby: ["Newport", "Barry", "Caerphilly", "Pontypridd"] },
  { city: "Newport", region: "South Wales", country: "Wales", nearby: ["Cardiff", "Cwmbran"] },
  { city: "Swansea", region: "South Wales", country: "Wales", nearby: ["Neath", "Port Talbot", "Llanelli"] },
  { city: "Barry", region: "South Wales", country: "Wales", nearby: ["Cardiff"] },
  { city: "Caerphilly", region: "South Wales", country: "Wales", nearby: ["Cardiff"] },
  { city: "Pontypridd", region: "South Wales", country: "Wales", nearby: ["Cardiff"] },
  { city: "Bridgend", region: "South Wales", country: "Wales", nearby: ["Cardiff", "Port Talbot"] },
  { city: "Neath", region: "South Wales", country: "Wales", nearby: ["Swansea", "Port Talbot"] },
  { city: "Port Talbot", region: "South Wales", country: "Wales", nearby: ["Swansea", "Neath"] },
  { city: "Llanelli", region: "South Wales", country: "Wales", nearby: ["Swansea"] },
  { city: "Merthyr Tydfil", region: "South Wales", country: "Wales" },
  { city: "Cwmbran", region: "South Wales", country: "Wales", nearby: ["Newport"] },
  { city: "Wrexham", region: "North Wales", country: "Wales", nearby: ["Chester"] },
  { city: "Bangor", region: "North Wales", country: "Wales" },
  { city: "Aberystwyth", region: "Mid Wales", country: "Wales" },
  { city: "St Davids", region: "Pembrokeshire", country: "Wales" },
  { city: "St Asaph", region: "Denbighshire", country: "Wales" },
  { city: "Carmarthen", region: "Carmarthenshire", country: "Wales" },

  // ===== Northern Ireland =====
  { city: "Belfast", region: "County Antrim", country: "Northern Ireland", nearby: ["Lisburn", "Bangor", "Newtownabbey"] },
  { city: "Lisburn", region: "County Antrim", country: "Northern Ireland", nearby: ["Belfast"] },
  { city: "Newtownabbey", region: "County Antrim", country: "Northern Ireland", nearby: ["Belfast"] },
  { city: "Bangor", region: "County Down", country: "Northern Ireland", nearby: ["Belfast"] },
  { city: "Londonderry", region: "County Londonderry", country: "Northern Ireland", nearby: ["Coleraine"] },
  { city: "Coleraine", region: "County Londonderry", country: "Northern Ireland", nearby: ["Londonderry"] },
  { city: "Armagh", region: "County Armagh", country: "Northern Ireland" },
  { city: "Newry", region: "County Down", country: "Northern Ireland" },
  { city: "Craigavon", region: "County Armagh", country: "Northern Ireland" },
  { city: "Ballymena", region: "County Antrim", country: "Northern Ireland" },
  { city: "Enniskillen", region: "County Fermanagh", country: "Northern Ireland" },
  { city: "Omagh", region: "County Tyrone", country: "Northern Ireland" },
];

const CITY_INDEX = new Map(UK_CITIES.map((c) => [c.city.toLowerCase(), c]));

export function findCity(name: string | null | undefined): UkCity | undefined {
  if (!name) return undefined;
  return CITY_INDEX.get(name.trim().toLowerCase());
}

export function isValidUkCity(name: string | null | undefined): boolean {
  return !!findCity(name);
}

/** Cities near the given city, including the city itself. Used for lead matching. */
export function nearbyCities(name: string): string[] {
  const c = findCity(name);
  if (!c) return [name];
  return [c.city, ...(c.nearby ?? [])];
}
