/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyShootbaseRouteImport } from './routes/why-shootbase'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NgRouteImport } from './routes/ng'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as GbRouteImport } from './routes/gb'
import { Route as ForProfessionalsRouteImport } from './routes/for-professionals'
import { Route as ForClientsRouteImport } from './routes/for-clients'
import { Route as CountryMismatchRouteImport } from './routes/country-mismatch'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffAcceptRouteImport } from './routes/staff.accept'
import { Route as ProfessionalsSignupRouteImport } from './routes/professionals.signup'
import { Route as ProfessionalsLoginRouteImport } from './routes/professionals.login'
import { Route as ProfessionalLoginRouteImport } from './routes/professional.login'
import { Route as ProInvoicesRouteImport } from './routes/pro.invoices'
import { Route as ProSlugRouteImport } from './routes/pro.$slug'
import { Route as PreviewNgRouteImport } from './routes/preview.ng'
import { Route as PreviewGbRouteImport } from './routes/preview.gb'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalPhotographerTermsRouteImport } from './routes/legal.photographer-terms'
import { Route as LegalGdprRouteImport } from './routes/legal.gdpr'
import { Route as LegalCustomerTermsRouteImport } from './routes/legal.customer-terms'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CustomerPostLeadRouteImport } from './routes/customer.post-lead'
import { Route as ClientSignupRouteImport } from './routes/client.signup'
import { Route as ClientLoginRouteImport } from './routes/client.login'
import { Route as AuthForgotRouteImport } from './routes/auth_.forgot'
import { Route as AuthVerifiedRouteImport } from './routes/auth.verified'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedReferRouteImport } from './routes/_authenticated/refer'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProfessionalDashboardRouteImport } from './routes/_authenticated/professional-dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreateInvoiceRouteImport } from './routes/_authenticated/create-invoice'
import { Route as AuthenticatedClientDashboardRouteImport } from './routes/_authenticated/client-dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ProInvoiceIdRouteImport } from './routes/pro.invoice.$id'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicSeedTestAccountsRouteImport } from './routes/api/public/seed-test-accounts'
import { Route as AuthenticatedThreadsIdRouteImport } from './routes/_authenticated/threads.$id'
import { Route as AuthenticatedProUnlockedRouteImport } from './routes/_authenticated/pro.unlocked'
import { Route as AuthenticatedProSettingsRouteImport } from './routes/_authenticated/pro.settings'
import { Route as AuthenticatedProResponsesRouteImport } from './routes/_authenticated/pro.responses'
import { Route as AuthenticatedProRefundsRouteImport } from './routes/_authenticated/pro.refunds'
import { Route as AuthenticatedProPostedJobsRouteImport } from './routes/_authenticated/pro.posted-jobs'
import { Route as AuthenticatedProOnboardingRouteImport } from './routes/_authenticated/pro.onboarding'
import { Route as AuthenticatedProLeadsRouteImport } from './routes/_authenticated/pro.leads'
import { Route as AuthenticatedProHelpRouteImport } from './routes/_authenticated/pro.help'
import { Route as AuthenticatedProDashboardRouteImport } from './routes/_authenticated/pro.dashboard'
import { Route as AuthenticatedProCreditsRouteImport } from './routes/_authenticated/pro.credits'
import { Route as AuthenticatedJobsIdRouteImport } from './routes/_authenticated/jobs.$id'
import { Route as AuthenticatedCustomerMessagesRouteImport } from './routes/_authenticated/customer.messages'
import { Route as AuthenticatedCreateInvoiceIdRouteImport } from './routes/_authenticated/create-invoice.$id'
import { Route as AuthenticatedCreateInvoiceEditorIdRouteImport } from './routes/_authenticated/create-invoice-editor.$id'
import { Route as AuthenticatedClientRecommendedProsRouteImport } from './routes/_authenticated/client.recommended-pros'
import { Route as AuthenticatedAdminVipRouteImport } from './routes/_authenticated/admin/vip'
import { Route as AuthenticatedAdminVideosRouteImport } from './routes/_authenticated/admin/videos'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin/tickets'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin/subscriptions'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRevenueRouteImport } from './routes/_authenticated/admin/revenue'
import { Route as AuthenticatedAdminPromosRouteImport } from './routes/_authenticated/admin/promos'
import { Route as AuthenticatedAdminLeadReportsRouteImport } from './routes/_authenticated/admin/lead-reports'
import { Route as AuthenticatedAdminLeadNotificationsRouteImport } from './routes/_authenticated/admin.lead-notifications'
import { Route as AuthenticatedAdminLeadDisputesRouteImport } from './routes/_authenticated/admin/lead-disputes'
import { Route as AuthenticatedAdminLaunchCleanupRouteImport } from './routes/_authenticated/admin/launch-cleanup'
import { Route as AuthenticatedAdminGeoRouteImport } from './routes/_authenticated/admin/geo'
import { Route as AuthenticatedAdminCountriesRouteImport } from './routes/_authenticated/admin/countries'
import { Route as AuthenticatedAdminCoinsRouteImport } from './routes/_authenticated/admin/coins'
import { Route as AuthenticatedAdminBankTransfersRouteImport } from './routes/_authenticated/admin/bank-transfers'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin/activity'
import { Route as AuthenticatedAccountSettingsRouteImport } from './routes/_authenticated/account.settings'
import { Route as AuthenticatedAdminTicketsIndexRouteImport } from './routes/_authenticated/admin/tickets.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicSupportInboundRouteImport } from './routes/api/public/support/inbound'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksSlaCheckRouteImport } from './routes/api/public/hooks/sla-check'
import { Route as ApiPublicHooksLeadNotificationsDispatchRouteImport } from './routes/api/public/hooks/lead-notifications-dispatch'
import { Route as ApiPublicHooksLeadDigestRouteImport } from './routes/api/public/hooks/lead-digest'
import { Route as ApiPublicAvatarProIdRouteImport } from './routes/api/public/avatar.$proId'
import { Route as AuthenticatedProCreditsSuccessRouteImport } from './routes/_authenticated/pro.credits.success'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin/users.$id'
import { Route as AuthenticatedAdminTicketsIdRouteImport } from './routes/_authenticated/admin/tickets.$id'
import { Route as ApiPublicPaymentsPaystackWebhookRouteImport } from './routes/api/public/payments/paystack/webhook'

const WhyShootbaseRoute = WhyShootbaseRouteImport.update({
  id: '/why-shootbase',
  path: '/why-shootbase',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NgRoute = NgRouteImport.update({
  id: '/ng',
  path: '/ng',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const GbRoute = GbRouteImport.update({
  id: '/gb',
  path: '/gb',
  getParentRoute: () => rootRouteImport,
} as any)
const ForProfessionalsRoute = ForProfessionalsRouteImport.update({
  id: '/for-professionals',
  path: '/for-professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const ForClientsRoute = ForClientsRouteImport.update({
  id: '/for-clients',
  path: '/for-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryMismatchRoute = CountryMismatchRouteImport.update({
  id: '/country-mismatch',
  path: '/country-mismatch',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAcceptRoute = StaffAcceptRouteImport.update({
  id: '/staff/accept',
  path: '/staff/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsSignupRoute = ProfessionalsSignupRouteImport.update({
  id: '/professionals/signup',
  path: '/professionals/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsLoginRoute = ProfessionalsLoginRouteImport.update({
  id: '/professionals/login',
  path: '/professionals/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalLoginRoute = ProfessionalLoginRouteImport.update({
  id: '/professional/login',
  path: '/professional/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProInvoicesRoute = ProInvoicesRouteImport.update({
  id: '/pro/invoices',
  path: '/pro/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSlugRoute = ProSlugRouteImport.update({
  id: '/pro/$slug',
  path: '/pro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewNgRoute = PreviewNgRouteImport.update({
  id: '/preview/ng',
  path: '/preview/ng',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewGbRoute = PreviewGbRouteImport.update({
  id: '/preview/gb',
  path: '/preview/gb',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPhotographerTermsRoute = LegalPhotographerTermsRouteImport.update({
  id: '/photographer-terms',
  path: '/photographer-terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalGdprRoute = LegalGdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCustomerTermsRoute = LegalCustomerTermsRouteImport.update({
  id: '/customer-terms',
  path: '/customer-terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPostLeadRoute = CustomerPostLeadRouteImport.update({
  id: '/customer/post-lead',
  path: '/customer/post-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSignupRoute = ClientSignupRouteImport.update({
  id: '/client/signup',
  path: '/client/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/client/login',
  path: '/client/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth_/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifiedRoute = AuthVerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => AuthRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReferRoute = AuthenticatedReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfessionalDashboardRoute =
  AuthenticatedProfessionalDashboardRouteImport.update({
    id: '/professional-dashboard',
    path: '/professional-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateInvoiceRoute =
  AuthenticatedCreateInvoiceRouteImport.update({
    id: '/create-invoice',
    path: '/create-invoice',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientDashboardRoute =
  AuthenticatedClientDashboardRouteImport.update({
    id: '/client-dashboard',
    path: '/client-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ProInvoiceIdRoute = ProInvoiceIdRouteImport.update({
  id: '/pro/invoice/$id',
  path: '/pro/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeedTestAccountsRoute =
  ApiPublicSeedTestAccountsRouteImport.update({
    id: '/api/public/seed-test-accounts',
    path: '/api/public/seed-test-accounts',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedThreadsIdRoute = AuthenticatedThreadsIdRouteImport.update({
  id: '/threads/$id',
  path: '/threads/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProUnlockedRoute =
  AuthenticatedProUnlockedRouteImport.update({
    id: '/pro/unlocked',
    path: '/pro/unlocked',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProSettingsRoute =
  AuthenticatedProSettingsRouteImport.update({
    id: '/pro/settings',
    path: '/pro/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProResponsesRoute =
  AuthenticatedProResponsesRouteImport.update({
    id: '/pro/responses',
    path: '/pro/responses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProRefundsRoute = AuthenticatedProRefundsRouteImport.update({
  id: '/pro/refunds',
  path: '/pro/refunds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProPostedJobsRoute =
  AuthenticatedProPostedJobsRouteImport.update({
    id: '/pro/posted-jobs',
    path: '/pro/posted-jobs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProOnboardingRoute =
  AuthenticatedProOnboardingRouteImport.update({
    id: '/pro/onboarding',
    path: '/pro/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProLeadsRoute = AuthenticatedProLeadsRouteImport.update({
  id: '/pro/leads',
  path: '/pro/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProHelpRoute = AuthenticatedProHelpRouteImport.update({
  id: '/pro/help',
  path: '/pro/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProDashboardRoute =
  AuthenticatedProDashboardRouteImport.update({
    id: '/pro/dashboard',
    path: '/pro/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProCreditsRoute = AuthenticatedProCreditsRouteImport.update({
  id: '/pro/credits',
  path: '/pro/credits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsIdRoute = AuthenticatedJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomerMessagesRoute =
  AuthenticatedCustomerMessagesRouteImport.update({
    id: '/customer/messages',
    path: '/customer/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreateInvoiceIdRoute =
  AuthenticatedCreateInvoiceIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCreateInvoiceRoute,
  } as any)
const AuthenticatedCreateInvoiceEditorIdRoute =
  AuthenticatedCreateInvoiceEditorIdRouteImport.update({
    id: '/create-invoice-editor/$id',
    path: '/create-invoice-editor/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientRecommendedProsRoute =
  AuthenticatedClientRecommendedProsRouteImport.update({
    id: '/client/recommended-pros',
    path: '/client/recommended-pros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVipRoute = AuthenticatedAdminVipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminVideosRoute =
  AuthenticatedAdminVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRevenueRoute =
  AuthenticatedAdminRevenueRouteImport.update({
    id: '/revenue',
    path: '/revenue',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPromosRoute =
  AuthenticatedAdminPromosRouteImport.update({
    id: '/promos',
    path: '/promos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLeadReportsRoute =
  AuthenticatedAdminLeadReportsRouteImport.update({
    id: '/lead-reports',
    path: '/lead-reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLeadNotificationsRoute =
  AuthenticatedAdminLeadNotificationsRouteImport.update({
    id: '/lead-notifications',
    path: '/lead-notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLeadDisputesRoute =
  AuthenticatedAdminLeadDisputesRouteImport.update({
    id: '/lead-disputes',
    path: '/lead-disputes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLaunchCleanupRoute =
  AuthenticatedAdminLaunchCleanupRouteImport.update({
    id: '/launch-cleanup',
    path: '/launch-cleanup',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGeoRoute = AuthenticatedAdminGeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCountriesRoute =
  AuthenticatedAdminCountriesRouteImport.update({
    id: '/countries',
    path: '/countries',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCoinsRoute = AuthenticatedAdminCoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminBankTransfersRoute =
  AuthenticatedAdminBankTransfersRouteImport.update({
    id: '/bank-transfers',
    path: '/bank-transfers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAccountSettingsRoute =
  AuthenticatedAccountSettingsRouteImport.update({
    id: '/account/settings',
    path: '/account/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTicketsIndexRoute =
  AuthenticatedAdminTicketsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminTicketsRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSupportInboundRoute = ApiPublicSupportInboundRouteImport.update({
  id: '/api/public/support/inbound',
  path: '/api/public/support/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSlaCheckRoute = ApiPublicHooksSlaCheckRouteImport.update({
  id: '/api/public/hooks/sla-check',
  path: '/api/public/hooks/sla-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksLeadNotificationsDispatchRoute =
  ApiPublicHooksLeadNotificationsDispatchRouteImport.update({
    id: '/api/public/hooks/lead-notifications-dispatch',
    path: '/api/public/hooks/lead-notifications-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLeadDigestRoute =
  ApiPublicHooksLeadDigestRouteImport.update({
    id: '/api/public/hooks/lead-digest',
    path: '/api/public/hooks/lead-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAvatarProIdRoute = ApiPublicAvatarProIdRouteImport.update({
  id: '/api/public/avatar/$proId',
  path: '/api/public/avatar/$proId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProCreditsSuccessRoute =
  AuthenticatedProCreditsSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AuthenticatedProCreditsRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminTicketsIdRoute =
  AuthenticatedAdminTicketsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminTicketsRoute,
  } as any)
const ApiPublicPaymentsPaystackWebhookRoute =
  ApiPublicPaymentsPaystackWebhookRouteImport.update({
    id: '/api/public/payments/paystack/webhook',
    path: '/api/public/payments/paystack/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/browse': typeof BrowseRoute
  '/country-mismatch': typeof CountryMismatchRoute
  '/for-clients': typeof ForClientsRoute
  '/for-professionals': typeof ForProfessionalsRoute
  '/gb': typeof GbRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/ng': typeof NgRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/why-shootbase': typeof WhyShootbaseRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/client-dashboard': typeof AuthenticatedClientDashboardRoute
  '/create-invoice': typeof AuthenticatedCreateInvoiceRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/professional-dashboard': typeof AuthenticatedProfessionalDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/refer': typeof AuthenticatedReferRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/client/login': typeof ClientLoginRoute
  '/client/signup': typeof ClientSignupRoute
  '/customer/post-lead': typeof CustomerPostLeadRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/customer-terms': typeof LegalCustomerTermsRoute
  '/legal/gdpr': typeof LegalGdprRoute
  '/legal/photographer-terms': typeof LegalPhotographerTermsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/preview/gb': typeof PreviewGbRoute
  '/preview/ng': typeof PreviewNgRoute
  '/pro/$slug': typeof ProSlugRoute
  '/pro/invoices': typeof ProInvoicesRoute
  '/professional/login': typeof ProfessionalLoginRoute
  '/professionals/login': typeof ProfessionalsLoginRoute
  '/professionals/signup': typeof ProfessionalsSignupRoute
  '/staff/accept': typeof StaffAcceptRoute
  '/account/settings': typeof AuthenticatedAccountSettingsRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bank-transfers': typeof AuthenticatedAdminBankTransfersRoute
  '/admin/coins': typeof AuthenticatedAdminCoinsRoute
  '/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/admin/geo': typeof AuthenticatedAdminGeoRoute
  '/admin/launch-cleanup': typeof AuthenticatedAdminLaunchCleanupRoute
  '/admin/lead-disputes': typeof AuthenticatedAdminLeadDisputesRoute
  '/admin/lead-notifications': typeof AuthenticatedAdminLeadNotificationsRoute
  '/admin/lead-reports': typeof AuthenticatedAdminLeadReportsRoute
  '/admin/promos': typeof AuthenticatedAdminPromosRoute
  '/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/admin/vip': typeof AuthenticatedAdminVipRoute
  '/client/recommended-pros': typeof AuthenticatedClientRecommendedProsRoute
  '/create-invoice-editor/$id': typeof AuthenticatedCreateInvoiceEditorIdRoute
  '/create-invoice/$id': typeof AuthenticatedCreateInvoiceIdRoute
  '/customer/messages': typeof AuthenticatedCustomerMessagesRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/pro/credits': typeof AuthenticatedProCreditsRouteWithChildren
  '/pro/dashboard': typeof AuthenticatedProDashboardRoute
  '/pro/help': typeof AuthenticatedProHelpRoute
  '/pro/leads': typeof AuthenticatedProLeadsRoute
  '/pro/onboarding': typeof AuthenticatedProOnboardingRoute
  '/pro/posted-jobs': typeof AuthenticatedProPostedJobsRoute
  '/pro/refunds': typeof AuthenticatedProRefundsRoute
  '/pro/responses': typeof AuthenticatedProResponsesRoute
  '/pro/settings': typeof AuthenticatedProSettingsRoute
  '/pro/unlocked': typeof AuthenticatedProUnlockedRoute
  '/threads/$id': typeof AuthenticatedThreadsIdRoute
  '/api/public/seed-test-accounts': typeof ApiPublicSeedTestAccountsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/pro/invoice/$id': typeof ProInvoiceIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/tickets/$id': typeof AuthenticatedAdminTicketsIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/pro/credits/success': typeof AuthenticatedProCreditsSuccessRoute
  '/api/public/avatar/$proId': typeof ApiPublicAvatarProIdRoute
  '/api/public/hooks/lead-digest': typeof ApiPublicHooksLeadDigestRoute
  '/api/public/hooks/lead-notifications-dispatch': typeof ApiPublicHooksLeadNotificationsDispatchRoute
  '/api/public/hooks/sla-check': typeof ApiPublicHooksSlaCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/support/inbound': typeof ApiPublicSupportInboundRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/tickets/': typeof AuthenticatedAdminTicketsIndexRoute
  '/api/public/payments/paystack/webhook': typeof ApiPublicPaymentsPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/browse': typeof BrowseRoute
  '/country-mismatch': typeof CountryMismatchRoute
  '/for-clients': typeof ForClientsRoute
  '/for-professionals': typeof ForProfessionalsRoute
  '/gb': typeof GbRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/ng': typeof NgRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/why-shootbase': typeof WhyShootbaseRoute
  '/client-dashboard': typeof AuthenticatedClientDashboardRoute
  '/create-invoice': typeof AuthenticatedCreateInvoiceRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/professional-dashboard': typeof AuthenticatedProfessionalDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/refer': typeof AuthenticatedReferRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/client/login': typeof ClientLoginRoute
  '/client/signup': typeof ClientSignupRoute
  '/customer/post-lead': typeof CustomerPostLeadRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/customer-terms': typeof LegalCustomerTermsRoute
  '/legal/gdpr': typeof LegalGdprRoute
  '/legal/photographer-terms': typeof LegalPhotographerTermsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/preview/gb': typeof PreviewGbRoute
  '/preview/ng': typeof PreviewNgRoute
  '/pro/$slug': typeof ProSlugRoute
  '/pro/invoices': typeof ProInvoicesRoute
  '/professional/login': typeof ProfessionalLoginRoute
  '/professionals/login': typeof ProfessionalsLoginRoute
  '/professionals/signup': typeof ProfessionalsSignupRoute
  '/staff/accept': typeof StaffAcceptRoute
  '/account/settings': typeof AuthenticatedAccountSettingsRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bank-transfers': typeof AuthenticatedAdminBankTransfersRoute
  '/admin/coins': typeof AuthenticatedAdminCoinsRoute
  '/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/admin/geo': typeof AuthenticatedAdminGeoRoute
  '/admin/launch-cleanup': typeof AuthenticatedAdminLaunchCleanupRoute
  '/admin/lead-disputes': typeof AuthenticatedAdminLeadDisputesRoute
  '/admin/lead-notifications': typeof AuthenticatedAdminLeadNotificationsRoute
  '/admin/lead-reports': typeof AuthenticatedAdminLeadReportsRoute
  '/admin/promos': typeof AuthenticatedAdminPromosRoute
  '/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/admin/vip': typeof AuthenticatedAdminVipRoute
  '/client/recommended-pros': typeof AuthenticatedClientRecommendedProsRoute
  '/create-invoice-editor/$id': typeof AuthenticatedCreateInvoiceEditorIdRoute
  '/create-invoice/$id': typeof AuthenticatedCreateInvoiceIdRoute
  '/customer/messages': typeof AuthenticatedCustomerMessagesRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/pro/credits': typeof AuthenticatedProCreditsRouteWithChildren
  '/pro/dashboard': typeof AuthenticatedProDashboardRoute
  '/pro/help': typeof AuthenticatedProHelpRoute
  '/pro/leads': typeof AuthenticatedProLeadsRoute
  '/pro/onboarding': typeof AuthenticatedProOnboardingRoute
  '/pro/posted-jobs': typeof AuthenticatedProPostedJobsRoute
  '/pro/refunds': typeof AuthenticatedProRefundsRoute
  '/pro/responses': typeof AuthenticatedProResponsesRoute
  '/pro/settings': typeof AuthenticatedProSettingsRoute
  '/pro/unlocked': typeof AuthenticatedProUnlockedRoute
  '/threads/$id': typeof AuthenticatedThreadsIdRoute
  '/api/public/seed-test-accounts': typeof ApiPublicSeedTestAccountsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/pro/invoice/$id': typeof ProInvoiceIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/tickets/$id': typeof AuthenticatedAdminTicketsIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/pro/credits/success': typeof AuthenticatedProCreditsSuccessRoute
  '/api/public/avatar/$proId': typeof ApiPublicAvatarProIdRoute
  '/api/public/hooks/lead-digest': typeof ApiPublicHooksLeadDigestRoute
  '/api/public/hooks/lead-notifications-dispatch': typeof ApiPublicHooksLeadNotificationsDispatchRoute
  '/api/public/hooks/sla-check': typeof ApiPublicHooksSlaCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/support/inbound': typeof ApiPublicSupportInboundRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsIndexRoute
  '/api/public/payments/paystack/webhook': typeof ApiPublicPaymentsPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/browse': typeof BrowseRoute
  '/country-mismatch': typeof CountryMismatchRoute
  '/for-clients': typeof ForClientsRoute
  '/for-professionals': typeof ForProfessionalsRoute
  '/gb': typeof GbRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/ng': typeof NgRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/why-shootbase': typeof WhyShootbaseRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/client-dashboard': typeof AuthenticatedClientDashboardRoute
  '/_authenticated/create-invoice': typeof AuthenticatedCreateInvoiceRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/professional-dashboard': typeof AuthenticatedProfessionalDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/refer': typeof AuthenticatedReferRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/auth_/forgot': typeof AuthForgotRoute
  '/client/login': typeof ClientLoginRoute
  '/client/signup': typeof ClientSignupRoute
  '/customer/post-lead': typeof CustomerPostLeadRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/customer-terms': typeof LegalCustomerTermsRoute
  '/legal/gdpr': typeof LegalGdprRoute
  '/legal/photographer-terms': typeof LegalPhotographerTermsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/preview/gb': typeof PreviewGbRoute
  '/preview/ng': typeof PreviewNgRoute
  '/pro/$slug': typeof ProSlugRoute
  '/pro/invoices': typeof ProInvoicesRoute
  '/professional/login': typeof ProfessionalLoginRoute
  '/professionals/login': typeof ProfessionalsLoginRoute
  '/professionals/signup': typeof ProfessionalsSignupRoute
  '/staff/accept': typeof StaffAcceptRoute
  '/_authenticated/account/settings': typeof AuthenticatedAccountSettingsRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/bank-transfers': typeof AuthenticatedAdminBankTransfersRoute
  '/_authenticated/admin/coins': typeof AuthenticatedAdminCoinsRoute
  '/_authenticated/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/_authenticated/admin/geo': typeof AuthenticatedAdminGeoRoute
  '/_authenticated/admin/launch-cleanup': typeof AuthenticatedAdminLaunchCleanupRoute
  '/_authenticated/admin/lead-disputes': typeof AuthenticatedAdminLeadDisputesRoute
  '/_authenticated/admin/lead-notifications': typeof AuthenticatedAdminLeadNotificationsRoute
  '/_authenticated/admin/lead-reports': typeof AuthenticatedAdminLeadReportsRoute
  '/_authenticated/admin/promos': typeof AuthenticatedAdminPromosRoute
  '/_authenticated/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/_authenticated/admin/vip': typeof AuthenticatedAdminVipRoute
  '/_authenticated/client/recommended-pros': typeof AuthenticatedClientRecommendedProsRoute
  '/_authenticated/create-invoice-editor/$id': typeof AuthenticatedCreateInvoiceEditorIdRoute
  '/_authenticated/create-invoice/$id': typeof AuthenticatedCreateInvoiceIdRoute
  '/_authenticated/customer/messages': typeof AuthenticatedCustomerMessagesRoute
  '/_authenticated/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/_authenticated/pro/credits': typeof AuthenticatedProCreditsRouteWithChildren
  '/_authenticated/pro/dashboard': typeof AuthenticatedProDashboardRoute
  '/_authenticated/pro/help': typeof AuthenticatedProHelpRoute
  '/_authenticated/pro/leads': typeof AuthenticatedProLeadsRoute
  '/_authenticated/pro/onboarding': typeof AuthenticatedProOnboardingRoute
  '/_authenticated/pro/posted-jobs': typeof AuthenticatedProPostedJobsRoute
  '/_authenticated/pro/refunds': typeof AuthenticatedProRefundsRoute
  '/_authenticated/pro/responses': typeof AuthenticatedProResponsesRoute
  '/_authenticated/pro/settings': typeof AuthenticatedProSettingsRoute
  '/_authenticated/pro/unlocked': typeof AuthenticatedProUnlockedRoute
  '/_authenticated/threads/$id': typeof AuthenticatedThreadsIdRoute
  '/api/public/seed-test-accounts': typeof ApiPublicSeedTestAccountsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/pro/invoice/$id': typeof ProInvoiceIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/tickets/$id': typeof AuthenticatedAdminTicketsIdRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/_authenticated/pro/credits/success': typeof AuthenticatedProCreditsSuccessRoute
  '/api/public/avatar/$proId': typeof ApiPublicAvatarProIdRoute
  '/api/public/hooks/lead-digest': typeof ApiPublicHooksLeadDigestRoute
  '/api/public/hooks/lead-notifications-dispatch': typeof ApiPublicHooksLeadNotificationsDispatchRoute
  '/api/public/hooks/sla-check': typeof ApiPublicHooksSlaCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/support/inbound': typeof ApiPublicSupportInboundRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/admin/tickets/': typeof AuthenticatedAdminTicketsIndexRoute
  '/api/public/payments/paystack/webhook': typeof ApiPublicPaymentsPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/country-mismatch'
    | '/for-clients'
    | '/for-professionals'
    | '/gb'
    | '/legal'
    | '/login'
    | '/ng'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/why-shootbase'
    | '/admin'
    | '/client-dashboard'
    | '/create-invoice'
    | '/dashboard'
    | '/help'
    | '/onboarding'
    | '/professional-dashboard'
    | '/profile'
    | '/refer'
    | '/admin/login'
    | '/auth/verified'
    | '/auth/forgot'
    | '/client/login'
    | '/client/signup'
    | '/customer/post-lead'
    | '/email/unsubscribe'
    | '/legal/cookies'
    | '/legal/customer-terms'
    | '/legal/gdpr'
    | '/legal/photographer-terms'
    | '/legal/privacy'
    | '/legal/terms'
    | '/preview/gb'
    | '/preview/ng'
    | '/pro/$slug'
    | '/pro/invoices'
    | '/professional/login'
    | '/professionals/login'
    | '/professionals/signup'
    | '/staff/accept'
    | '/account/settings'
    | '/admin/activity'
    | '/admin/audit'
    | '/admin/bank-transfers'
    | '/admin/coins'
    | '/admin/countries'
    | '/admin/geo'
    | '/admin/launch-cleanup'
    | '/admin/lead-disputes'
    | '/admin/lead-notifications'
    | '/admin/lead-reports'
    | '/admin/promos'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscriptions'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/videos'
    | '/admin/vip'
    | '/client/recommended-pros'
    | '/create-invoice-editor/$id'
    | '/create-invoice/$id'
    | '/customer/messages'
    | '/jobs/$id'
    | '/pro/credits'
    | '/pro/dashboard'
    | '/pro/help'
    | '/pro/leads'
    | '/pro/onboarding'
    | '/pro/posted-jobs'
    | '/pro/refunds'
    | '/pro/responses'
    | '/pro/settings'
    | '/pro/unlocked'
    | '/threads/$id'
    | '/api/public/seed-test-accounts'
    | '/lovable/email/suppression'
    | '/pro/invoice/$id'
    | '/admin/'
    | '/admin/tickets/$id'
    | '/admin/users/$id'
    | '/pro/credits/success'
    | '/api/public/avatar/$proId'
    | '/api/public/hooks/lead-digest'
    | '/api/public/hooks/lead-notifications-dispatch'
    | '/api/public/hooks/sla-check'
    | '/api/public/payments/webhook'
    | '/api/public/support/inbound'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/tickets/'
    | '/api/public/payments/paystack/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/country-mismatch'
    | '/for-clients'
    | '/for-professionals'
    | '/gb'
    | '/legal'
    | '/login'
    | '/ng'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/why-shootbase'
    | '/client-dashboard'
    | '/create-invoice'
    | '/dashboard'
    | '/help'
    | '/onboarding'
    | '/professional-dashboard'
    | '/profile'
    | '/refer'
    | '/admin/login'
    | '/auth/verified'
    | '/auth/forgot'
    | '/client/login'
    | '/client/signup'
    | '/customer/post-lead'
    | '/email/unsubscribe'
    | '/legal/cookies'
    | '/legal/customer-terms'
    | '/legal/gdpr'
    | '/legal/photographer-terms'
    | '/legal/privacy'
    | '/legal/terms'
    | '/preview/gb'
    | '/preview/ng'
    | '/pro/$slug'
    | '/pro/invoices'
    | '/professional/login'
    | '/professionals/login'
    | '/professionals/signup'
    | '/staff/accept'
    | '/account/settings'
    | '/admin/activity'
    | '/admin/audit'
    | '/admin/bank-transfers'
    | '/admin/coins'
    | '/admin/countries'
    | '/admin/geo'
    | '/admin/launch-cleanup'
    | '/admin/lead-disputes'
    | '/admin/lead-notifications'
    | '/admin/lead-reports'
    | '/admin/promos'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/admin/videos'
    | '/admin/vip'
    | '/client/recommended-pros'
    | '/create-invoice-editor/$id'
    | '/create-invoice/$id'
    | '/customer/messages'
    | '/jobs/$id'
    | '/pro/credits'
    | '/pro/dashboard'
    | '/pro/help'
    | '/pro/leads'
    | '/pro/onboarding'
    | '/pro/posted-jobs'
    | '/pro/refunds'
    | '/pro/responses'
    | '/pro/settings'
    | '/pro/unlocked'
    | '/threads/$id'
    | '/api/public/seed-test-accounts'
    | '/lovable/email/suppression'
    | '/pro/invoice/$id'
    | '/admin'
    | '/admin/tickets/$id'
    | '/admin/users/$id'
    | '/pro/credits/success'
    | '/api/public/avatar/$proId'
    | '/api/public/hooks/lead-digest'
    | '/api/public/hooks/lead-notifications-dispatch'
    | '/api/public/hooks/sla-check'
    | '/api/public/payments/webhook'
    | '/api/public/support/inbound'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/tickets'
    | '/api/public/payments/paystack/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/country-mismatch'
    | '/for-clients'
    | '/for-professionals'
    | '/gb'
    | '/legal'
    | '/login'
    | '/ng'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/why-shootbase'
    | '/_authenticated/admin'
    | '/_authenticated/client-dashboard'
    | '/_authenticated/create-invoice'
    | '/_authenticated/dashboard'
    | '/_authenticated/help'
    | '/_authenticated/onboarding'
    | '/_authenticated/professional-dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/refer'
    | '/admin/login'
    | '/auth/verified'
    | '/auth_/forgot'
    | '/client/login'
    | '/client/signup'
    | '/customer/post-lead'
    | '/email/unsubscribe'
    | '/legal/cookies'
    | '/legal/customer-terms'
    | '/legal/gdpr'
    | '/legal/photographer-terms'
    | '/legal/privacy'
    | '/legal/terms'
    | '/preview/gb'
    | '/preview/ng'
    | '/pro/$slug'
    | '/pro/invoices'
    | '/professional/login'
    | '/professionals/login'
    | '/professionals/signup'
    | '/staff/accept'
    | '/_authenticated/account/settings'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/bank-transfers'
    | '/_authenticated/admin/coins'
    | '/_authenticated/admin/countries'
    | '/_authenticated/admin/geo'
    | '/_authenticated/admin/launch-cleanup'
    | '/_authenticated/admin/lead-disputes'
    | '/_authenticated/admin/lead-notifications'
    | '/_authenticated/admin/lead-reports'
    | '/_authenticated/admin/promos'
    | '/_authenticated/admin/revenue'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/videos'
    | '/_authenticated/admin/vip'
    | '/_authenticated/client/recommended-pros'
    | '/_authenticated/create-invoice-editor/$id'
    | '/_authenticated/create-invoice/$id'
    | '/_authenticated/customer/messages'
    | '/_authenticated/jobs/$id'
    | '/_authenticated/pro/credits'
    | '/_authenticated/pro/dashboard'
    | '/_authenticated/pro/help'
    | '/_authenticated/pro/leads'
    | '/_authenticated/pro/onboarding'
    | '/_authenticated/pro/posted-jobs'
    | '/_authenticated/pro/refunds'
    | '/_authenticated/pro/responses'
    | '/_authenticated/pro/settings'
    | '/_authenticated/pro/unlocked'
    | '/_authenticated/threads/$id'
    | '/api/public/seed-test-accounts'
    | '/lovable/email/suppression'
    | '/pro/invoice/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/tickets/$id'
    | '/_authenticated/admin/users/$id'
    | '/_authenticated/pro/credits/success'
    | '/api/public/avatar/$proId'
    | '/api/public/hooks/lead-digest'
    | '/api/public/hooks/lead-notifications-dispatch'
    | '/api/public/hooks/sla-check'
    | '/api/public/payments/webhook'
    | '/api/public/support/inbound'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/admin/tickets/'
    | '/api/public/payments/paystack/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  CountryMismatchRoute: typeof CountryMismatchRoute
  ForClientsRoute: typeof ForClientsRoute
  ForProfessionalsRoute: typeof ForProfessionalsRoute
  GbRoute: typeof GbRoute
  LegalRoute: typeof LegalRouteWithChildren
  LoginRoute: typeof LoginRoute
  NgRoute: typeof NgRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WhyShootbaseRoute: typeof WhyShootbaseRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthForgotRoute: typeof AuthForgotRoute
  ClientLoginRoute: typeof ClientLoginRoute
  ClientSignupRoute: typeof ClientSignupRoute
  CustomerPostLeadRoute: typeof CustomerPostLeadRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PreviewGbRoute: typeof PreviewGbRoute
  PreviewNgRoute: typeof PreviewNgRoute
  ProSlugRoute: typeof ProSlugRoute
  ProInvoicesRoute: typeof ProInvoicesRoute
  ProfessionalLoginRoute: typeof ProfessionalLoginRoute
  ProfessionalsLoginRoute: typeof ProfessionalsLoginRoute
  ProfessionalsSignupRoute: typeof ProfessionalsSignupRoute
  StaffAcceptRoute: typeof StaffAcceptRoute
  ApiPublicSeedTestAccountsRoute: typeof ApiPublicSeedTestAccountsRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ProInvoiceIdRoute: typeof ProInvoiceIdRoute
  ApiPublicAvatarProIdRoute: typeof ApiPublicAvatarProIdRoute
  ApiPublicHooksLeadDigestRoute: typeof ApiPublicHooksLeadDigestRoute
  ApiPublicHooksLeadNotificationsDispatchRoute: typeof ApiPublicHooksLeadNotificationsDispatchRoute
  ApiPublicHooksSlaCheckRoute: typeof ApiPublicHooksSlaCheckRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicSupportInboundRoute: typeof ApiPublicSupportInboundRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicPaymentsPaystackWebhookRoute: typeof ApiPublicPaymentsPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-shootbase': {
      id: '/why-shootbase'
      path: '/why-shootbase'
      fullPath: '/why-shootbase'
      preLoaderRoute: typeof WhyShootbaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ng': {
      id: '/ng'
      path: '/ng'
      fullPath: '/ng'
      preLoaderRoute: typeof NgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gb': {
      id: '/gb'
      path: '/gb'
      fullPath: '/gb'
      preLoaderRoute: typeof GbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-professionals': {
      id: '/for-professionals'
      path: '/for-professionals'
      fullPath: '/for-professionals'
      preLoaderRoute: typeof ForProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-clients': {
      id: '/for-clients'
      path: '/for-clients'
      fullPath: '/for-clients'
      preLoaderRoute: typeof ForClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country-mismatch': {
      id: '/country-mismatch'
      path: '/country-mismatch'
      fullPath: '/country-mismatch'
      preLoaderRoute: typeof CountryMismatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/accept': {
      id: '/staff/accept'
      path: '/staff/accept'
      fullPath: '/staff/accept'
      preLoaderRoute: typeof StaffAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals/signup': {
      id: '/professionals/signup'
      path: '/professionals/signup'
      fullPath: '/professionals/signup'
      preLoaderRoute: typeof ProfessionalsSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals/login': {
      id: '/professionals/login'
      path: '/professionals/login'
      fullPath: '/professionals/login'
      preLoaderRoute: typeof ProfessionalsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional/login': {
      id: '/professional/login'
      path: '/professional/login'
      fullPath: '/professional/login'
      preLoaderRoute: typeof ProfessionalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/invoices': {
      id: '/pro/invoices'
      path: '/pro/invoices'
      fullPath: '/pro/invoices'
      preLoaderRoute: typeof ProInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/$slug': {
      id: '/pro/$slug'
      path: '/pro/$slug'
      fullPath: '/pro/$slug'
      preLoaderRoute: typeof ProSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/ng': {
      id: '/preview/ng'
      path: '/preview/ng'
      fullPath: '/preview/ng'
      preLoaderRoute: typeof PreviewNgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/gb': {
      id: '/preview/gb'
      path: '/preview/gb'
      fullPath: '/preview/gb'
      preLoaderRoute: typeof PreviewGbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/photographer-terms': {
      id: '/legal/photographer-terms'
      path: '/photographer-terms'
      fullPath: '/legal/photographer-terms'
      preLoaderRoute: typeof LegalPhotographerTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/gdpr': {
      id: '/legal/gdpr'
      path: '/gdpr'
      fullPath: '/legal/gdpr'
      preLoaderRoute: typeof LegalGdprRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/customer-terms': {
      id: '/legal/customer-terms'
      path: '/customer-terms'
      fullPath: '/legal/customer-terms'
      preLoaderRoute: typeof LegalCustomerTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/post-lead': {
      id: '/customer/post-lead'
      path: '/customer/post-lead'
      fullPath: '/customer/post-lead'
      preLoaderRoute: typeof CustomerPostLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/signup': {
      id: '/client/signup'
      path: '/client/signup'
      fullPath: '/client/signup'
      preLoaderRoute: typeof ClientSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/login': {
      id: '/client/login'
      path: '/client/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/forgot': {
      id: '/auth_/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verified': {
      id: '/auth/verified'
      path: '/verified'
      fullPath: '/auth/verified'
      preLoaderRoute: typeof AuthVerifiedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/refer': {
      id: '/_authenticated/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof AuthenticatedReferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professional-dashboard': {
      id: '/_authenticated/professional-dashboard'
      path: '/professional-dashboard'
      fullPath: '/professional-dashboard'
      preLoaderRoute: typeof AuthenticatedProfessionalDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create-invoice': {
      id: '/_authenticated/create-invoice'
      path: '/create-invoice'
      fullPath: '/create-invoice'
      preLoaderRoute: typeof AuthenticatedCreateInvoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client-dashboard': {
      id: '/_authenticated/client-dashboard'
      path: '/client-dashboard'
      fullPath: '/client-dashboard'
      preLoaderRoute: typeof AuthenticatedClientDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/pro/invoice/$id': {
      id: '/pro/invoice/$id'
      path: '/pro/invoice/$id'
      fullPath: '/pro/invoice/$id'
      preLoaderRoute: typeof ProInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-test-accounts': {
      id: '/api/public/seed-test-accounts'
      path: '/api/public/seed-test-accounts'
      fullPath: '/api/public/seed-test-accounts'
      preLoaderRoute: typeof ApiPublicSeedTestAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/threads/$id': {
      id: '/_authenticated/threads/$id'
      path: '/threads/$id'
      fullPath: '/threads/$id'
      preLoaderRoute: typeof AuthenticatedThreadsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/unlocked': {
      id: '/_authenticated/pro/unlocked'
      path: '/pro/unlocked'
      fullPath: '/pro/unlocked'
      preLoaderRoute: typeof AuthenticatedProUnlockedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/settings': {
      id: '/_authenticated/pro/settings'
      path: '/pro/settings'
      fullPath: '/pro/settings'
      preLoaderRoute: typeof AuthenticatedProSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/responses': {
      id: '/_authenticated/pro/responses'
      path: '/pro/responses'
      fullPath: '/pro/responses'
      preLoaderRoute: typeof AuthenticatedProResponsesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/refunds': {
      id: '/_authenticated/pro/refunds'
      path: '/pro/refunds'
      fullPath: '/pro/refunds'
      preLoaderRoute: typeof AuthenticatedProRefundsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/posted-jobs': {
      id: '/_authenticated/pro/posted-jobs'
      path: '/pro/posted-jobs'
      fullPath: '/pro/posted-jobs'
      preLoaderRoute: typeof AuthenticatedProPostedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/onboarding': {
      id: '/_authenticated/pro/onboarding'
      path: '/pro/onboarding'
      fullPath: '/pro/onboarding'
      preLoaderRoute: typeof AuthenticatedProOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/leads': {
      id: '/_authenticated/pro/leads'
      path: '/pro/leads'
      fullPath: '/pro/leads'
      preLoaderRoute: typeof AuthenticatedProLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/help': {
      id: '/_authenticated/pro/help'
      path: '/pro/help'
      fullPath: '/pro/help'
      preLoaderRoute: typeof AuthenticatedProHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/dashboard': {
      id: '/_authenticated/pro/dashboard'
      path: '/pro/dashboard'
      fullPath: '/pro/dashboard'
      preLoaderRoute: typeof AuthenticatedProDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/credits': {
      id: '/_authenticated/pro/credits'
      path: '/pro/credits'
      fullPath: '/pro/credits'
      preLoaderRoute: typeof AuthenticatedProCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$id': {
      id: '/_authenticated/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthenticatedJobsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer/messages': {
      id: '/_authenticated/customer/messages'
      path: '/customer/messages'
      fullPath: '/customer/messages'
      preLoaderRoute: typeof AuthenticatedCustomerMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create-invoice/$id': {
      id: '/_authenticated/create-invoice/$id'
      path: '/$id'
      fullPath: '/create-invoice/$id'
      preLoaderRoute: typeof AuthenticatedCreateInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedCreateInvoiceRoute
    }
    '/_authenticated/create-invoice-editor/$id': {
      id: '/_authenticated/create-invoice-editor/$id'
      path: '/create-invoice-editor/$id'
      fullPath: '/create-invoice-editor/$id'
      preLoaderRoute: typeof AuthenticatedCreateInvoiceEditorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/recommended-pros': {
      id: '/_authenticated/client/recommended-pros'
      path: '/client/recommended-pros'
      fullPath: '/client/recommended-pros'
      preLoaderRoute: typeof AuthenticatedClientRecommendedProsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/vip': {
      id: '/_authenticated/admin/vip'
      path: '/vip'
      fullPath: '/admin/vip'
      preLoaderRoute: typeof AuthenticatedAdminVipRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/videos': {
      id: '/_authenticated/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AuthenticatedAdminVideosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/revenue': {
      id: '/_authenticated/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AuthenticatedAdminRevenueRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/promos': {
      id: '/_authenticated/admin/promos'
      path: '/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AuthenticatedAdminPromosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/lead-reports': {
      id: '/_authenticated/admin/lead-reports'
      path: '/lead-reports'
      fullPath: '/admin/lead-reports'
      preLoaderRoute: typeof AuthenticatedAdminLeadReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/lead-notifications': {
      id: '/_authenticated/admin/lead-notifications'
      path: '/lead-notifications'
      fullPath: '/admin/lead-notifications'
      preLoaderRoute: typeof AuthenticatedAdminLeadNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/lead-disputes': {
      id: '/_authenticated/admin/lead-disputes'
      path: '/lead-disputes'
      fullPath: '/admin/lead-disputes'
      preLoaderRoute: typeof AuthenticatedAdminLeadDisputesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/launch-cleanup': {
      id: '/_authenticated/admin/launch-cleanup'
      path: '/launch-cleanup'
      fullPath: '/admin/launch-cleanup'
      preLoaderRoute: typeof AuthenticatedAdminLaunchCleanupRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/geo': {
      id: '/_authenticated/admin/geo'
      path: '/geo'
      fullPath: '/admin/geo'
      preLoaderRoute: typeof AuthenticatedAdminGeoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/countries': {
      id: '/_authenticated/admin/countries'
      path: '/countries'
      fullPath: '/admin/countries'
      preLoaderRoute: typeof AuthenticatedAdminCountriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/coins': {
      id: '/_authenticated/admin/coins'
      path: '/coins'
      fullPath: '/admin/coins'
      preLoaderRoute: typeof AuthenticatedAdminCoinsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bank-transfers': {
      id: '/_authenticated/admin/bank-transfers'
      path: '/bank-transfers'
      fullPath: '/admin/bank-transfers'
      preLoaderRoute: typeof AuthenticatedAdminBankTransfersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/account/settings': {
      id: '/_authenticated/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AuthenticatedAccountSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tickets/': {
      id: '/_authenticated/admin/tickets/'
      path: '/'
      fullPath: '/admin/tickets/'
      preLoaderRoute: typeof AuthenticatedAdminTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminTicketsRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/support/inbound': {
      id: '/api/public/support/inbound'
      path: '/api/public/support/inbound'
      fullPath: '/api/public/support/inbound'
      preLoaderRoute: typeof ApiPublicSupportInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sla-check': {
      id: '/api/public/hooks/sla-check'
      path: '/api/public/hooks/sla-check'
      fullPath: '/api/public/hooks/sla-check'
      preLoaderRoute: typeof ApiPublicHooksSlaCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/lead-notifications-dispatch': {
      id: '/api/public/hooks/lead-notifications-dispatch'
      path: '/api/public/hooks/lead-notifications-dispatch'
      fullPath: '/api/public/hooks/lead-notifications-dispatch'
      preLoaderRoute: typeof ApiPublicHooksLeadNotificationsDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/lead-digest': {
      id: '/api/public/hooks/lead-digest'
      path: '/api/public/hooks/lead-digest'
      fullPath: '/api/public/hooks/lead-digest'
      preLoaderRoute: typeof ApiPublicHooksLeadDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/avatar/$proId': {
      id: '/api/public/avatar/$proId'
      path: '/api/public/avatar/$proId'
      fullPath: '/api/public/avatar/$proId'
      preLoaderRoute: typeof ApiPublicAvatarProIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pro/credits/success': {
      id: '/_authenticated/pro/credits/success'
      path: '/success'
      fullPath: '/pro/credits/success'
      preLoaderRoute: typeof AuthenticatedProCreditsSuccessRouteImport
      parentRoute: typeof AuthenticatedProCreditsRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/tickets/$id': {
      id: '/_authenticated/admin/tickets/$id'
      path: '/$id'
      fullPath: '/admin/tickets/$id'
      preLoaderRoute: typeof AuthenticatedAdminTicketsIdRouteImport
      parentRoute: typeof AuthenticatedAdminTicketsRoute
    }
    '/api/public/payments/paystack/webhook': {
      id: '/api/public/payments/paystack/webhook'
      path: '/api/public/payments/paystack/webhook'
      fullPath: '/api/public/payments/paystack/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminTicketsRouteChildren {
  AuthenticatedAdminTicketsIdRoute: typeof AuthenticatedAdminTicketsIdRoute
  AuthenticatedAdminTicketsIndexRoute: typeof AuthenticatedAdminTicketsIndexRoute
}

const AuthenticatedAdminTicketsRouteChildren: AuthenticatedAdminTicketsRouteChildren =
  {
    AuthenticatedAdminTicketsIdRoute: AuthenticatedAdminTicketsIdRoute,
    AuthenticatedAdminTicketsIndexRoute: AuthenticatedAdminTicketsIndexRoute,
  }

const AuthenticatedAdminTicketsRouteWithChildren =
  AuthenticatedAdminTicketsRoute._addFileChildren(
    AuthenticatedAdminTicketsRouteChildren,
  )

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBankTransfersRoute: typeof AuthenticatedAdminBankTransfersRoute
  AuthenticatedAdminCoinsRoute: typeof AuthenticatedAdminCoinsRoute
  AuthenticatedAdminCountriesRoute: typeof AuthenticatedAdminCountriesRoute
  AuthenticatedAdminGeoRoute: typeof AuthenticatedAdminGeoRoute
  AuthenticatedAdminLaunchCleanupRoute: typeof AuthenticatedAdminLaunchCleanupRoute
  AuthenticatedAdminLeadDisputesRoute: typeof AuthenticatedAdminLeadDisputesRoute
  AuthenticatedAdminLeadNotificationsRoute: typeof AuthenticatedAdminLeadNotificationsRoute
  AuthenticatedAdminLeadReportsRoute: typeof AuthenticatedAdminLeadReportsRoute
  AuthenticatedAdminPromosRoute: typeof AuthenticatedAdminPromosRoute
  AuthenticatedAdminRevenueRoute: typeof AuthenticatedAdminRevenueRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAdminVideosRoute: typeof AuthenticatedAdminVideosRoute
  AuthenticatedAdminVipRoute: typeof AuthenticatedAdminVipRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminBankTransfersRoute: AuthenticatedAdminBankTransfersRoute,
    AuthenticatedAdminCoinsRoute: AuthenticatedAdminCoinsRoute,
    AuthenticatedAdminCountriesRoute: AuthenticatedAdminCountriesRoute,
    AuthenticatedAdminGeoRoute: AuthenticatedAdminGeoRoute,
    AuthenticatedAdminLaunchCleanupRoute: AuthenticatedAdminLaunchCleanupRoute,
    AuthenticatedAdminLeadDisputesRoute: AuthenticatedAdminLeadDisputesRoute,
    AuthenticatedAdminLeadNotificationsRoute:
      AuthenticatedAdminLeadNotificationsRoute,
    AuthenticatedAdminLeadReportsRoute: AuthenticatedAdminLeadReportsRoute,
    AuthenticatedAdminPromosRoute: AuthenticatedAdminPromosRoute,
    AuthenticatedAdminRevenueRoute: AuthenticatedAdminRevenueRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
    AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
    AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRouteWithChildren,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
    AuthenticatedAdminVideosRoute: AuthenticatedAdminVideosRoute,
    AuthenticatedAdminVipRoute: AuthenticatedAdminVipRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedCreateInvoiceRouteChildren {
  AuthenticatedCreateInvoiceIdRoute: typeof AuthenticatedCreateInvoiceIdRoute
}

const AuthenticatedCreateInvoiceRouteChildren: AuthenticatedCreateInvoiceRouteChildren =
  {
    AuthenticatedCreateInvoiceIdRoute: AuthenticatedCreateInvoiceIdRoute,
  }

const AuthenticatedCreateInvoiceRouteWithChildren =
  AuthenticatedCreateInvoiceRoute._addFileChildren(
    AuthenticatedCreateInvoiceRouteChildren,
  )

interface AuthenticatedProCreditsRouteChildren {
  AuthenticatedProCreditsSuccessRoute: typeof AuthenticatedProCreditsSuccessRoute
}

const AuthenticatedProCreditsRouteChildren: AuthenticatedProCreditsRouteChildren =
  {
    AuthenticatedProCreditsSuccessRoute: AuthenticatedProCreditsSuccessRoute,
  }

const AuthenticatedProCreditsRouteWithChildren =
  AuthenticatedProCreditsRoute._addFileChildren(
    AuthenticatedProCreditsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedClientDashboardRoute: typeof AuthenticatedClientDashboardRoute
  AuthenticatedCreateInvoiceRoute: typeof AuthenticatedCreateInvoiceRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfessionalDashboardRoute: typeof AuthenticatedProfessionalDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferRoute: typeof AuthenticatedReferRoute
  AuthenticatedAccountSettingsRoute: typeof AuthenticatedAccountSettingsRoute
  AuthenticatedClientRecommendedProsRoute: typeof AuthenticatedClientRecommendedProsRoute
  AuthenticatedCreateInvoiceEditorIdRoute: typeof AuthenticatedCreateInvoiceEditorIdRoute
  AuthenticatedCustomerMessagesRoute: typeof AuthenticatedCustomerMessagesRoute
  AuthenticatedJobsIdRoute: typeof AuthenticatedJobsIdRoute
  AuthenticatedProCreditsRoute: typeof AuthenticatedProCreditsRouteWithChildren
  AuthenticatedProDashboardRoute: typeof AuthenticatedProDashboardRoute
  AuthenticatedProHelpRoute: typeof AuthenticatedProHelpRoute
  AuthenticatedProLeadsRoute: typeof AuthenticatedProLeadsRoute
  AuthenticatedProOnboardingRoute: typeof AuthenticatedProOnboardingRoute
  AuthenticatedProPostedJobsRoute: typeof AuthenticatedProPostedJobsRoute
  AuthenticatedProRefundsRoute: typeof AuthenticatedProRefundsRoute
  AuthenticatedProResponsesRoute: typeof AuthenticatedProResponsesRoute
  AuthenticatedProSettingsRoute: typeof AuthenticatedProSettingsRoute
  AuthenticatedProUnlockedRoute: typeof AuthenticatedProUnlockedRoute
  AuthenticatedThreadsIdRoute: typeof AuthenticatedThreadsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedClientDashboardRoute: AuthenticatedClientDashboardRoute,
  AuthenticatedCreateInvoiceRoute: AuthenticatedCreateInvoiceRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfessionalDashboardRoute:
    AuthenticatedProfessionalDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferRoute: AuthenticatedReferRoute,
  AuthenticatedAccountSettingsRoute: AuthenticatedAccountSettingsRoute,
  AuthenticatedClientRecommendedProsRoute:
    AuthenticatedClientRecommendedProsRoute,
  AuthenticatedCreateInvoiceEditorIdRoute:
    AuthenticatedCreateInvoiceEditorIdRoute,
  AuthenticatedCustomerMessagesRoute: AuthenticatedCustomerMessagesRoute,
  AuthenticatedJobsIdRoute: AuthenticatedJobsIdRoute,
  AuthenticatedProCreditsRoute: AuthenticatedProCreditsRouteWithChildren,
  AuthenticatedProDashboardRoute: AuthenticatedProDashboardRoute,
  AuthenticatedProHelpRoute: AuthenticatedProHelpRoute,
  AuthenticatedProLeadsRoute: AuthenticatedProLeadsRoute,
  AuthenticatedProOnboardingRoute: AuthenticatedProOnboardingRoute,
  AuthenticatedProPostedJobsRoute: AuthenticatedProPostedJobsRoute,
  AuthenticatedProRefundsRoute: AuthenticatedProRefundsRoute,
  AuthenticatedProResponsesRoute: AuthenticatedProResponsesRoute,
  AuthenticatedProSettingsRoute: AuthenticatedProSettingsRoute,
  AuthenticatedProUnlockedRoute: AuthenticatedProUnlockedRoute,
  AuthenticatedThreadsIdRoute: AuthenticatedThreadsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthVerifiedRoute: typeof AuthVerifiedRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthVerifiedRoute: AuthVerifiedRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LegalRouteChildren {
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalCustomerTermsRoute: typeof LegalCustomerTermsRoute
  LegalGdprRoute: typeof LegalGdprRoute
  LegalPhotographerTermsRoute: typeof LegalPhotographerTermsRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalCookiesRoute: LegalCookiesRoute,
  LegalCustomerTermsRoute: LegalCustomerTermsRoute,
  LegalGdprRoute: LegalGdprRoute,
  LegalPhotographerTermsRoute: LegalPhotographerTermsRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BrowseRoute: BrowseRoute,
  CountryMismatchRoute: CountryMismatchRoute,
  ForClientsRoute: ForClientsRoute,
  ForProfessionalsRoute: ForProfessionalsRoute,
  GbRoute: GbRoute,
  LegalRoute: LegalRouteWithChildren,
  LoginRoute: LoginRoute,
  NgRoute: NgRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WhyShootbaseRoute: WhyShootbaseRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthForgotRoute: AuthForgotRoute,
  ClientLoginRoute: ClientLoginRoute,
  ClientSignupRoute: ClientSignupRoute,
  CustomerPostLeadRoute: CustomerPostLeadRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PreviewGbRoute: PreviewGbRoute,
  PreviewNgRoute: PreviewNgRoute,
  ProSlugRoute: ProSlugRoute,
  ProInvoicesRoute: ProInvoicesRoute,
  ProfessionalLoginRoute: ProfessionalLoginRoute,
  ProfessionalsLoginRoute: ProfessionalsLoginRoute,
  ProfessionalsSignupRoute: ProfessionalsSignupRoute,
  StaffAcceptRoute: StaffAcceptRoute,
  ApiPublicSeedTestAccountsRoute: ApiPublicSeedTestAccountsRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ProInvoiceIdRoute: ProInvoiceIdRoute,
  ApiPublicAvatarProIdRoute: ApiPublicAvatarProIdRoute,
  ApiPublicHooksLeadDigestRoute: ApiPublicHooksLeadDigestRoute,
  ApiPublicHooksLeadNotificationsDispatchRoute:
    ApiPublicHooksLeadNotificationsDispatchRoute,
  ApiPublicHooksSlaCheckRoute: ApiPublicHooksSlaCheckRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicSupportInboundRoute: ApiPublicSupportInboundRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicPaymentsPaystackWebhookRoute: ApiPublicPaymentsPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
